import "dotenv/config";
import type { Config } from "drizzle-kit";

// NOTE: migrations in src/db/migrations are HAND-AUTHORED (reviewed line-by-line
// before apply), not generated by drizzle-kit — pgvector's CREATE EXTENSION and
// the HNSW index aren't cleanly expressible via `drizzle-kit generate`. This
// config exists for parity + tooling (e.g. `drizzle-kit studio`); `out` points
// at the same hand-authored directory the migrate runner reads.
export default {
  schema: "./src/db/schema.ts",
  out: "./src/db/migrations",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL ?? "",
  },
} satisfies Config;
